# settings.yaml

base_dir: "/home/user/rss_scraper/db_data"

max_concurrent_requests: 5   # контроль параллелизма

rss:
  interfax:
    - "https://www.interfax.ru/rss.asp"
  prime:
    - "https://1prime.ru/export/rss2/archive/index.xml"
  investing:
    - "https://ru.investing.com/rss/286.rss"
    - "https://ru.investing.com/rss/290.rss"
    - "https://ru.investing.com/rss/302.rss"
    - "https://ru.investing.com/rss/bonds.rss"
    - "https://ru.investing.com/rss/bonds_Opinion.rss"
    - "https://ru.investing.com/rss/commodities.rss"
    - "https://ru.investing.com/rss/commodities_Energy.rss"
    - "https://ru.investing.com/rss/commodities_Fundamental.rss"
    - "https://ru.investing.com/rss/commodities_Metals.rss"
    - "https://ru.investing.com/rss/commodities_Opinion.rss"
    - "https://ru.investing.com/rss/commodities_Strategy.rss"
    - "https://ru.investing.com/rss/commodities_Technical.rss"
    - "https://ru.investing.com/rss/forex.rss"
    - "https://ru.investing.com/rss/forex_Fundamental.rss"
    - "https://ru.investing.com/rss/forex_Opinion.rss"
    - "https://ru.investing.com/rss/forex_Signals.rss"
    - "https://ru.investing.com/rss/forex_Technical.rss"
    - "https://ru.investing.com/rss/market_overview.rss"
    - "https://ru.investing.com/rss/market_overview_Fundamental.rss"
    - "https://ru.investing.com/rss/market_overview_Opinion.rss"
    - "https://ru.investing.com/rss/market_overview_Technical.rss"
    - "https://ru.investing.com/rss/market_overview_investing_ideas.rss"
    - "https://ru.investing.com/rss/news.rss"
    - "https://ru.investing.com/rss/news_1.rss"
    - "https://ru.investing.com/rss/news_1061.rss"
    - "https://ru.investing.com/rss/news_1062.rss"
    - "https://ru.investing.com/rss/news_1063.rss"
    - "https://ru.investing.com/rss/news_1064.rss"
    - "https://ru.investing.com/rss/news_1065.rss"
    - "https://ru.investing.com/rss/news_11.rss"
    - "https://ru.investing.com/rss/news_12.rss"
    - "https://ru.investing.com/rss/news_14.rss"
    - "https://ru.investing.com/rss/news_25.rss"
    - "https://ru.investing.com/rss/news_285.rss"
    - "https://ru.investing.com/rss/news_287.rss"
    - "https://ru.investing.com/rss/news_301.rss"
    - "https://ru.investing.com/rss/news_356.rss"
    - "https://ru.investing.com/rss/news_357.rss"
    - "https://ru.investing.com/rss/news_95.rss"
    - "https://ru.investing.com/rss/stock.rss"
    - "https://ru.investing.com/rss/stock_Fundamental.rss"
    - "https://ru.investing.com/rss/stock_Stocks.rss"
    - "https://ru.investing.com/rss/stock_Technical.rss"
    - "https://ru.investing.com/rss/stock_stock_picks.rss"
