# mix/settings.yaml

ticker: 'MIX'
ticker_lc: 'mix'
provider: 'investing'
model_name: 'bge-m3'
url_ai: 'http://localhost:11434/api/embeddings'
min_prev_files: 2
max_prev_files: 10  # Максимальное количество md файлов для прогноза
time_start: '21:00:00'
time_end: '20:59:59'
num_mds: 100  # Количество последних интервалов для сохранения в markdown файлы
num_dbs: 4  # Количество последних файлов БД новостей для обработки
start_date_download_minutes: '2025-06-24'  # Дата начала загрузки минутных свечей
test_days: 22  # Количество дней для тестирования
end_date_limit: "2025-10-15"  # Дата окончания обработки данных rts_backtest_multi_max_investing_by_date.py
start_date: "2025-07-01"  # Дата начала динамического rts_backtesting_dynamic_max_investing_by_date.py

md_path: 'C:/Users/Alkor/gd/md_{ticker_lc}_{provider}'
cache_file: 'C:/Users/Alkor/PycharmProjects/beget_rss/{ticker_lc}/{ticker_lc}_embeddings_{provider}_ollama.pkl'
output_dir: 'C:/Users/Alkor/gd/predict_ai/{ticker_lc}_{provider}_ollama'
log_dir: 'C:/Users/Alkor/gd/predict_ai/{ticker_lc}_{provider}_ollama/log'
path_db_minute: 'C:/Users/Alkor/gd/data_quote_db/{ticker}_futures_minute_2025.db'
path_db_day: 'C:/Users/Alkor/gd/data_quote_db/{ticker}_futures_day_2025_21-00.db'
db_news_dir: 'C:/Users/Alkor/gd/db_rss_{provider}'